entities:
    - 'investigator'
    - 'study'
    - 'study_file'
    - 'family'
    - 'participant'
    - 'family_relationship'
    - 'diagnosis'
    - 'phenotype'
    - 'outcome'
    - 'biospecimen'
    - 'sequencing_experiment'
    - 'genomic_file'

extract:
  data_dir: '/Users/singhn4/Projects/kids_first/data/Rios_Wise_2016'

transform:
  mappings_file: '/Users/singhn4/backup-kf-api-dataservice/dataservice/util/data_import/rios/mappings.py'

load:
    use: kf_dataservice_load
    # use: db_load
    kf_dataservice_load:
        base_url: 'http://localhost:5000'
drop_data:
    study: SD_VMK01DZK
